// Generated file, do NOT edit

import {
  $229Q as Test_229Q,
  $236B as Test_236B,
  $26DV as Test_26DV,
  $27NA as Test_27NA,
  $2AUY as Test_2AUY,
  $2CMS as Test_2CMS,
  $2EBW as Test_2EBW,
  $2G84 as Test_2G84,
  $2JQS as Test_2JQS,
  $2LFX as Test_2LFX,
  $2SXE as Test_2SXE,
  $2XXW as Test_2XXW,
  $33X3 as Test_33X3,
  $35KP as Test_35KP,
  $36F6 as Test_36F6,
  $3ALJ as Test_3ALJ,
  $3GZX as Test_3GZX,
  $3HFZ as Test_3HFZ,
  $3MYT as Test_3MYT,
  $3R3P as Test_3R3P,
  $3RLN as Test_3RLN,
  $3UYS as Test_3UYS,
  $4ABK as Test_4ABK,
  $4CQQ as Test_4CQQ,
  $4EJS as Test_4EJS,
  $4FJ6 as Test_4FJ6,
  $4GC6 as Test_4GC6,
  $4H7K as Test_4H7K,
  $4HVU as Test_4HVU,
  $4JVG as Test_4JVG,
  $4MUZ as Test_4MUZ,
  $4Q9F as Test_4Q9F,
  $4QFQ as Test_4QFQ,
  $4RWC as Test_4RWC,
  $4UYU as Test_4UYU,
  $4V8U as Test_4V8U,
  $4WA9 as Test_4WA9,
  $4ZYM as Test_4ZYM,
  $52DL as Test_52DL,
  $54T7 as Test_54T7,
  $55WF as Test_55WF,
  $565N as Test_565N,
  $57H4 as Test_57H4,
  $58MP as Test_58MP,
  $5BVJ as Test_5BVJ,
  $5C5M as Test_5C5M,
  $5GBF as Test_5GBF,
  $5KJE as Test_5KJE,
  $5LLU as Test_5LLU,
  $5MUD as Test_5MUD,
  $5NYZ as Test_5NYZ,
  $5T43 as Test_5T43,
  $5TRB as Test_5TRB,
  $5TYM as Test_5TYM,
  $5U3A as Test_5U3A,
  $5WE3 as Test_5WE3,
  $62EZ as Test_62EZ,
  $652Z as Test_652Z,
  $65WH as Test_65WH,
  $6BCT as Test_6BCT,
  $6BFJ as Test_6BFJ,
  $6CA3 as Test_6CA3,
  $6CK3 as Test_6CK3,
  $6FWR as Test_6FWR,
  $6H3V as Test_6H3V,
  $6HB6 as Test_6HB6,
  $6JQW as Test_6JQW,
  $6JTT as Test_6JTT,
  $6JWB as Test_6JWB,
  $6KGN as Test_6KGN,
  $6LVF as Test_6LVF,
  $6M2F as Test_6M2F,
  $6PBE as Test_6PBE,
  $6S55 as Test_6S55,
  $6SLA as Test_6SLA,
  $6VJK as Test_6VJK,
  $6WLZ as Test_6WLZ,
  $6WPF as Test_6WPF,
  $6XDY as Test_6XDY,
  $6ZKB as Test_6ZKB,
  $735Y as Test_735Y,
  $74H7 as Test_74H7,
  $753E as Test_753E,
  $7A4E as Test_7A4E,
  $7BMT as Test_7BMT,
  $7BUB as Test_7BUB,
  $7FWL as Test_7FWL,
  $7LBH as Test_7LBH,
  $7MNF as Test_7MNF,
  $7T8X as Test_7T8X,
  $7TMG as Test_7TMG,
  $7W2P as Test_7W2P,
  $7Z25 as Test_7Z25,
  $7ZZ5 as Test_7ZZ5,
  $82AN as Test_82AN,
  $87E4 as Test_87E4,
  $8CWC as Test_8CWC,
  $8G76 as Test_8G76,
  $8KB6 as Test_8KB6,
  $8MK2 as Test_8MK2,
  $8QBE as Test_8QBE,
  $8UDB as Test_8UDB,
  $8XDJ as Test_8XDJ,
  $8XYN as Test_8XYN,
  $93JH as Test_93JH,
  $93WF as Test_93WF,
  $96L6 as Test_96L6,
  $96NN as Test_96NN,
  $98YD as Test_98YD,
  $9BXH as Test_9BXH,
  $9C9N as Test_9C9N,
  $9CWY as Test_9CWY,
  $9DXL as Test_9DXL,
  $9FMG as Test_9FMG,
  $9HCY as Test_9HCY,
  $9J7A as Test_9J7A,
  $9JBA as Test_9JBA,
  $9KAX as Test_9KAX,
  $9KBC as Test_9KBC,
  $9MAG as Test_9MAG,
  $9MMA as Test_9MMA,
  $9MMW as Test_9MMW,
  $9MQT as Test_9MQT,
  $9SA2 as Test_9SA2,
  $9SHH as Test_9SHH,
  $9TFX as Test_9TFX,
  $9U5K as Test_9U5K,
  $9WXW as Test_9WXW,
  $9YRD as Test_9YRD,
  $A2M4 as Test_A2M4,
  $A6F9 as Test_A6F9,
  $A984 as Test_A984,
  $AB8U as Test_AB8U,
  $AVM7 as Test_AVM7,
  $AZ63 as Test_AZ63,
  $AZW3 as Test_AZW3,
  $B3HG as Test_B3HG,
  $B63P as Test_B63P,
  $BD7L as Test_BD7L,
  $BEC7 as Test_BEC7,
  $BF9H as Test_BF9H,
  $BS4K as Test_BS4K,
  $BU8L as Test_BU8L,
  $C2DT as Test_C2DT,
  $C2SP as Test_C2SP,
  $C4HZ as Test_C4HZ,
  $CC74 as Test_CC74,
  $CFD4 as Test_CFD4,
  $CML9 as Test_CML9,
  $CN3R as Test_CN3R,
  $CPZ3 as Test_CPZ3,
  $CQ3W as Test_CQ3W,
  $CT4Q as Test_CT4Q,
  $CTN5 as Test_CTN5,
  $CUP7 as Test_CUP7,
  $CVW2 as Test_CVW2,
  $CXX2 as Test_CXX2,
  $D49Q as Test_D49Q,
  $D83L as Test_D83L,
  $D88J as Test_D88J,
  $D9TU as Test_D9TU,
  $DBG4 as Test_DBG4,
  $DC7X as Test_DC7X,
  $DE56 as Test_DE56,
  $DFF7 as Test_DFF7,
  $DHP8 as Test_DHP8,
  $DK3J as Test_DK3J,
  $DK4H as Test_DK4H,
  $DK95 as Test_DK95,
  $DMG6 as Test_DMG6,
  $DWX9 as Test_DWX9,
  $E76Z as Test_E76Z,
  $EB22 as Test_EB22,
  $EHF6 as Test_EHF6,
  $EW3V as Test_EW3V,
  $EX5H as Test_EX5H,
  $EXG3 as Test_EXG3,
  $F2C7 as Test_F2C7,
  $F3CP as Test_F3CP,
  $F6MC as Test_F6MC,
  $F8F9 as Test_F8F9,
  $FBC9 as Test_FBC9,
  $FH7J as Test_FH7J,
  $FP8R as Test_FP8R,
  $FQ7F as Test_FQ7F,
  $FRK4 as Test_FRK4,
  $FTA2 as Test_FTA2,
  $FUP4 as Test_FUP4,
  $G4RS as Test_G4RS,
  $G5U8 as Test_G5U8,
  $G7JE as Test_G7JE,
  $G992 as Test_G992,
  $G9HC as Test_G9HC,
  $GDY7 as Test_GDY7,
  $GH63 as Test_GH63,
  $GT5M as Test_GT5M,
  $H2RW as Test_H2RW,
  $H3Z8 as Test_H3Z8,
  $H7J7 as Test_H7J7,
  $H7TQ as Test_H7TQ,
  $HM87 as Test_HM87,
  $HMK4 as Test_HMK4,
  $HMQ5 as Test_HMQ5,
  $HRE5 as Test_HRE5,
  $HS5T as Test_HS5T,
  $HU3P as Test_HU3P,
  $HWV9 as Test_HWV9,
  $J3BT as Test_J3BT,
  $J5UC as Test_J5UC,
  $J7PZ as Test_J7PZ,
  $J7VC as Test_J7VC,
  $J9HZ as Test_J9HZ,
  $JEF9 as Test_JEF9,
  $JHB9 as Test_JHB9,
  $JKF3 as Test_JKF3,
  $JQ4R as Test_JQ4R,
  $JR7V as Test_JR7V,
  $JS2J as Test_JS2J,
  $JTV5 as Test_JTV5,
  $JY7Z as Test_JY7Z,
  $K3WX as Test_K3WX,
  $K4SU as Test_K4SU,
  $K527 as Test_K527,
  $K54U as Test_K54U,
  $K858 as Test_K858,
  $KH5V as Test_KH5V,
  $KK5P as Test_KK5P,
  $KMK3 as Test_KMK3,
  $KS4U as Test_KS4U,
  $KSS4 as Test_KSS4,
  $L24T as Test_L24T,
  $L383 as Test_L383,
  $L94M as Test_L94M,
  $L9U5 as Test_L9U5,
  $LE5A as Test_LE5A,
  $LHL4 as Test_LHL4,
  $LP6E as Test_LP6E,
  $LQZ7 as Test_LQZ7,
  $LX3P as Test_LX3P,
  $M29M as Test_M29M,
  $M2N8 as Test_M2N8,
  $M5C3 as Test_M5C3,
  $M5DY as Test_M5DY,
  $M6YH as Test_M6YH,
  $M7A3 as Test_M7A3,
  $M7NX as Test_M7NX,
  $M9B4 as Test_M9B4,
  $MJS9 as Test_MJS9,
  $MUS6 as Test_MUS6,
  $MXS3 as Test_MXS3,
  $MYW6 as Test_MYW6,
  $MZX3 as Test_MZX3,
  $N4JP as Test_N4JP,
  $N782 as Test_N782,
  $NAT4 as Test_NAT4,
  $NB6Z as Test_NB6Z,
  $NHX8 as Test_NHX8,
  $NJ66 as Test_NJ66,
  $NKF9 as Test_NKF9,
  $NP9H as Test_NP9H,
  $P2AD as Test_P2AD,
  $P2EQ as Test_P2EQ,
  $P76L as Test_P76L,
  $P94K as Test_P94K,
  $PBJ2 as Test_PBJ2,
  $PRH3 as Test_PRH3,
  $PUW8 as Test_PUW8,
  $PW8X as Test_PW8X,
  $Q4CL as Test_Q4CL,
  $Q5MG as Test_Q5MG,
  $Q88A as Test_Q88A,
  $Q8AD as Test_Q8AD,
  $Q9WF as Test_Q9WF,
  $QB6E as Test_QB6E,
  $QF4Y as Test_QF4Y,
  $QLJ7 as Test_QLJ7,
  $QT73 as Test_QT73,
  $R4YG as Test_R4YG,
  $R52L as Test_R52L,
  $RHX7 as Test_RHX7,
  $RLU9 as Test_RLU9,
  $RR7F as Test_RR7F,
  $RTP8 as Test_RTP8,
  $RXY3 as Test_RXY3,
  $RZP5 as Test_RZP5,
  $RZT7 as Test_RZT7,
  $S3PD as Test_S3PD,
  $S4GJ as Test_S4GJ,
  $S4JQ as Test_S4JQ,
  $S4T7 as Test_S4T7,
  $S7BG as Test_S7BG,
  $S98Z as Test_S98Z,
  $S9E8 as Test_S9E8,
  $SBG9 as Test_SBG9,
  $SF5V as Test_SF5V,
  $SKE5 as Test_SKE5,
  $SM9W as Test_SM9W,
  $SR86 as Test_SR86,
  $SSW6 as Test_SSW6,
  $SU5Z as Test_SU5Z,
  $SU74 as Test_SU74,
  $SY6V as Test_SY6V,
  $SYW4 as Test_SYW4,
  $T26H as Test_T26H,
  $T4YY as Test_T4YY,
  $T5N4 as Test_T5N4,
  $T833 as Test_T833,
  $TD5N as Test_TD5N,
  $TE2A as Test_TE2A,
  $TL85 as Test_TL85,
  $TS54 as Test_TS54,
  $U3C3 as Test_U3C3,
  $U3XV as Test_U3XV,
  $U44R as Test_U44R,
  $U99R as Test_U99R,
  $U9NS as Test_U9NS,
  $UDM2 as Test_UDM2,
  $UDR7 as Test_UDR7,
  $UGM3 as Test_UGM3,
  $UKK6 as Test_UKK6,
  $UT92 as Test_UT92,
  $UV7Q as Test_UV7Q,
  $V55R as Test_V55R,
  $V9D5 as Test_V9D5,
  $VJP3 as Test_VJP3,
  $W42U as Test_W42U,
  $W4TN as Test_W4TN,
  $W5VH as Test_W5VH,
  $W9L4 as Test_W9L4,
  $WZ62 as Test_WZ62,
  $X38W as Test_X38W,
  $X4QW as Test_X4QW,
  $X8DW as Test_X8DW,
  $XLQ9 as Test_XLQ9,
  $XV9V as Test_XV9V,
  $XW4D as Test_XW4D,
  $Y2GN as Test_Y2GN,
  $Y79Y as Test_Y79Y,
  $YD5X as Test_YD5X,
  $YJV2 as Test_YJV2,
  $Z67P as Test_Z67P,
  $Z9M4 as Test_Z9M4,
  $ZCZ6 as Test_ZCZ6,
  $ZF4X as Test_ZF4X,
  $ZH7C as Test_ZH7C,
  $ZK9H as Test_ZK9H,
  $ZL4Z as Test_ZL4Z,
  $ZVH3 as Test_ZVH3,
  $ZWK4 as Test_ZWK4,
  $ZXT5 as Test_ZXT5,
} from './data/index.js'

declare const Suite: readonly [
  typeof Test_229Q,
  typeof Test_236B,
  typeof Test_26DV,
  typeof Test_27NA,
  typeof Test_2AUY,
  typeof Test_2CMS,
  typeof Test_2EBW,
  typeof Test_2G84,
  typeof Test_2JQS,
  typeof Test_2LFX,
  typeof Test_2SXE,
  typeof Test_2XXW,
  typeof Test_33X3,
  typeof Test_35KP,
  typeof Test_36F6,
  typeof Test_3ALJ,
  typeof Test_3GZX,
  typeof Test_3HFZ,
  typeof Test_3MYT,
  typeof Test_3R3P,
  typeof Test_3RLN,
  typeof Test_3UYS,
  typeof Test_4ABK,
  typeof Test_4CQQ,
  typeof Test_4EJS,
  typeof Test_4FJ6,
  typeof Test_4GC6,
  typeof Test_4H7K,
  typeof Test_4HVU,
  typeof Test_4JVG,
  typeof Test_4MUZ,
  typeof Test_4Q9F,
  typeof Test_4QFQ,
  typeof Test_4RWC,
  typeof Test_4UYU,
  typeof Test_4V8U,
  typeof Test_4WA9,
  typeof Test_4ZYM,
  typeof Test_52DL,
  typeof Test_54T7,
  typeof Test_55WF,
  typeof Test_565N,
  typeof Test_57H4,
  typeof Test_58MP,
  typeof Test_5BVJ,
  typeof Test_5C5M,
  typeof Test_5GBF,
  typeof Test_5KJE,
  typeof Test_5LLU,
  typeof Test_5MUD,
  typeof Test_5NYZ,
  typeof Test_5T43,
  typeof Test_5TRB,
  typeof Test_5TYM,
  typeof Test_5U3A,
  typeof Test_5WE3,
  typeof Test_62EZ,
  typeof Test_652Z,
  typeof Test_65WH,
  typeof Test_6BCT,
  typeof Test_6BFJ,
  typeof Test_6CA3,
  typeof Test_6CK3,
  typeof Test_6FWR,
  typeof Test_6H3V,
  typeof Test_6HB6,
  typeof Test_6JQW,
  typeof Test_6JTT,
  typeof Test_6JWB,
  typeof Test_6KGN,
  typeof Test_6LVF,
  typeof Test_6M2F,
  typeof Test_6PBE,
  typeof Test_6S55,
  typeof Test_6SLA,
  typeof Test_6VJK,
  typeof Test_6WLZ,
  typeof Test_6WPF,
  typeof Test_6XDY,
  typeof Test_6ZKB,
  typeof Test_735Y,
  typeof Test_74H7,
  typeof Test_753E,
  typeof Test_7A4E,
  typeof Test_7BMT,
  typeof Test_7BUB,
  typeof Test_7FWL,
  typeof Test_7LBH,
  typeof Test_7MNF,
  typeof Test_7T8X,
  typeof Test_7TMG,
  typeof Test_7W2P,
  typeof Test_7Z25,
  typeof Test_7ZZ5,
  typeof Test_82AN,
  typeof Test_87E4,
  typeof Test_8CWC,
  typeof Test_8G76,
  typeof Test_8KB6,
  typeof Test_8MK2,
  typeof Test_8QBE,
  typeof Test_8UDB,
  typeof Test_8XDJ,
  typeof Test_8XYN,
  typeof Test_93JH,
  typeof Test_93WF,
  typeof Test_96L6,
  typeof Test_96NN,
  typeof Test_98YD,
  typeof Test_9BXH,
  typeof Test_9C9N,
  typeof Test_9CWY,
  typeof Test_9DXL,
  typeof Test_9FMG,
  typeof Test_9HCY,
  typeof Test_9J7A,
  typeof Test_9JBA,
  typeof Test_9KAX,
  typeof Test_9KBC,
  typeof Test_9MAG,
  typeof Test_9MMA,
  typeof Test_9MMW,
  typeof Test_9MQT,
  typeof Test_9SA2,
  typeof Test_9SHH,
  typeof Test_9TFX,
  typeof Test_9U5K,
  typeof Test_9WXW,
  typeof Test_9YRD,
  typeof Test_A2M4,
  typeof Test_A6F9,
  typeof Test_A984,
  typeof Test_AB8U,
  typeof Test_AVM7,
  typeof Test_AZ63,
  typeof Test_AZW3,
  typeof Test_B3HG,
  typeof Test_B63P,
  typeof Test_BD7L,
  typeof Test_BEC7,
  typeof Test_BF9H,
  typeof Test_BS4K,
  typeof Test_BU8L,
  typeof Test_C2DT,
  typeof Test_C2SP,
  typeof Test_C4HZ,
  typeof Test_CC74,
  typeof Test_CFD4,
  typeof Test_CML9,
  typeof Test_CN3R,
  typeof Test_CPZ3,
  typeof Test_CQ3W,
  typeof Test_CT4Q,
  typeof Test_CTN5,
  typeof Test_CUP7,
  typeof Test_CVW2,
  typeof Test_CXX2,
  typeof Test_D49Q,
  typeof Test_D83L,
  typeof Test_D88J,
  typeof Test_D9TU,
  typeof Test_DBG4,
  typeof Test_DC7X,
  typeof Test_DE56,
  typeof Test_DFF7,
  typeof Test_DHP8,
  typeof Test_DK3J,
  typeof Test_DK4H,
  typeof Test_DK95,
  typeof Test_DMG6,
  typeof Test_DWX9,
  typeof Test_E76Z,
  typeof Test_EB22,
  typeof Test_EHF6,
  typeof Test_EW3V,
  typeof Test_EX5H,
  typeof Test_EXG3,
  typeof Test_F2C7,
  typeof Test_F3CP,
  typeof Test_F6MC,
  typeof Test_F8F9,
  typeof Test_FBC9,
  typeof Test_FH7J,
  typeof Test_FP8R,
  typeof Test_FQ7F,
  typeof Test_FRK4,
  typeof Test_FTA2,
  typeof Test_FUP4,
  typeof Test_G4RS,
  typeof Test_G5U8,
  typeof Test_G7JE,
  typeof Test_G992,
  typeof Test_G9HC,
  typeof Test_GDY7,
  typeof Test_GH63,
  typeof Test_GT5M,
  typeof Test_H2RW,
  typeof Test_H3Z8,
  typeof Test_H7J7,
  typeof Test_H7TQ,
  typeof Test_HM87,
  typeof Test_HMK4,
  typeof Test_HMQ5,
  typeof Test_HRE5,
  typeof Test_HS5T,
  typeof Test_HU3P,
  typeof Test_HWV9,
  typeof Test_J3BT,
  typeof Test_J5UC,
  typeof Test_J7PZ,
  typeof Test_J7VC,
  typeof Test_J9HZ,
  typeof Test_JEF9,
  typeof Test_JHB9,
  typeof Test_JKF3,
  typeof Test_JQ4R,
  typeof Test_JR7V,
  typeof Test_JS2J,
  typeof Test_JTV5,
  typeof Test_JY7Z,
  typeof Test_K3WX,
  typeof Test_K4SU,
  typeof Test_K527,
  typeof Test_K54U,
  typeof Test_K858,
  typeof Test_KH5V,
  typeof Test_KK5P,
  typeof Test_KMK3,
  typeof Test_KS4U,
  typeof Test_KSS4,
  typeof Test_L24T,
  typeof Test_L383,
  typeof Test_L94M,
  typeof Test_L9U5,
  typeof Test_LE5A,
  typeof Test_LHL4,
  typeof Test_LP6E,
  typeof Test_LQZ7,
  typeof Test_LX3P,
  typeof Test_M29M,
  typeof Test_M2N8,
  typeof Test_M5C3,
  typeof Test_M5DY,
  typeof Test_M6YH,
  typeof Test_M7A3,
  typeof Test_M7NX,
  typeof Test_M9B4,
  typeof Test_MJS9,
  typeof Test_MUS6,
  typeof Test_MXS3,
  typeof Test_MYW6,
  typeof Test_MZX3,
  typeof Test_N4JP,
  typeof Test_N782,
  typeof Test_NAT4,
  typeof Test_NB6Z,
  typeof Test_NHX8,
  typeof Test_NJ66,
  typeof Test_NKF9,
  typeof Test_NP9H,
  typeof Test_P2AD,
  typeof Test_P2EQ,
  typeof Test_P76L,
  typeof Test_P94K,
  typeof Test_PBJ2,
  typeof Test_PRH3,
  typeof Test_PUW8,
  typeof Test_PW8X,
  typeof Test_Q4CL,
  typeof Test_Q5MG,
  typeof Test_Q88A,
  typeof Test_Q8AD,
  typeof Test_Q9WF,
  typeof Test_QB6E,
  typeof Test_QF4Y,
  typeof Test_QLJ7,
  typeof Test_QT73,
  typeof Test_R4YG,
  typeof Test_R52L,
  typeof Test_RHX7,
  typeof Test_RLU9,
  typeof Test_RR7F,
  typeof Test_RTP8,
  typeof Test_RXY3,
  typeof Test_RZP5,
  typeof Test_RZT7,
  typeof Test_S3PD,
  typeof Test_S4GJ,
  typeof Test_S4JQ,
  typeof Test_S4T7,
  typeof Test_S7BG,
  typeof Test_S98Z,
  typeof Test_S9E8,
  typeof Test_SBG9,
  typeof Test_SF5V,
  typeof Test_SKE5,
  typeof Test_SM9W,
  typeof Test_SR86,
  typeof Test_SSW6,
  typeof Test_SU5Z,
  typeof Test_SU74,
  typeof Test_SY6V,
  typeof Test_SYW4,
  typeof Test_T26H,
  typeof Test_T4YY,
  typeof Test_T5N4,
  typeof Test_T833,
  typeof Test_TD5N,
  typeof Test_TE2A,
  typeof Test_TL85,
  typeof Test_TS54,
  typeof Test_U3C3,
  typeof Test_U3XV,
  typeof Test_U44R,
  typeof Test_U99R,
  typeof Test_U9NS,
  typeof Test_UDM2,
  typeof Test_UDR7,
  typeof Test_UGM3,
  typeof Test_UKK6,
  typeof Test_UT92,
  typeof Test_UV7Q,
  typeof Test_V55R,
  typeof Test_V9D5,
  typeof Test_VJP3,
  typeof Test_W42U,
  typeof Test_W4TN,
  typeof Test_W5VH,
  typeof Test_W9L4,
  typeof Test_WZ62,
  typeof Test_X38W,
  typeof Test_X4QW,
  typeof Test_X8DW,
  typeof Test_XLQ9,
  typeof Test_XV9V,
  typeof Test_XW4D,
  typeof Test_Y2GN,
  typeof Test_Y79Y,
  typeof Test_YD5X,
  typeof Test_YJV2,
  typeof Test_Z67P,
  typeof Test_Z9M4,
  typeof Test_ZCZ6,
  typeof Test_ZF4X,
  typeof Test_ZH7C,
  typeof Test_ZK9H,
  typeof Test_ZL4Z,
  typeof Test_ZVH3,
  typeof Test_ZWK4,
  typeof Test_ZXT5,
]

export default Suite
